src/main/java/model/Person.java
package model;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Embedded;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import controller.EmbeddedMutable;


@Entity
@Table(name = "PERSON")
public class Person implements Serializable, Keyable, Mutable {
	
	private static final long serialVersionUID = 1L;
	
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private Integer id;
	
	private String name;
	
	private String vorname;
	
	private String email;
	
	private String telefon;
	
	private Boolean juristisch;
	
	@Embedded
	private EmbeddedMutable mutable = new EmbeddedMutable();

	@Override
	public Integer getId() {
		return id;
	}

	@Override
	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getVorname() {
		return vorname;
	}

	public void setVorname(String vorname) {
		this.vorname = vorname;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getTelefon() {
		return telefon;
	}

	public void setTelefon(String telefon) {
		this.telefon = telefon;
	}

	public Boolean getJuristisch() {
		return juristisch;
	}

	public void setJuristisch(Boolean juristisch) {
		this.juristisch = juristisch;
	}

	public EmbeddedMutable getMutable() {
		return mutable;
	}

	public void setMutable(EmbeddedMutable mutable) {
		this.mutable = mutable;
	}
	
	public String getFullName(){
		return name + " " + vorname;
	}

	@Override
    public Date getMutiertam() {
        return mutable.getMutiertam();
    }

    @Override
    public User getMutiertvon() {
        return mutable.getMutiertvon();
    }

    @Override
    public void setMutiertam(Date mutiertam) {
        mutable.setMutiertam(mutiertam);
    }

    @Override
    public void setMutiertvon(User mutiertvon) {
        mutable.setMutiertvon(mutiertvon);
    }
	
}

src/main/java/model/Salt.java
package model;

import java.io.Serializable;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.security.NoSuchProviderException;
import java.security.SecureRandom;
import java.util.Date;

import javax.persistence.Embedded;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import controller.EmbeddedMutable;

@Entity
@Table(name = "SALT")
public class Salt implements Serializable, Keyable, Mutable{
	

	private static final long serialVersionUID = 6452366309968252633L;

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private Integer id;
	
	private String salt;
	
	@Embedded
	private EmbeddedMutable mutable = new EmbeddedMutable();

	@Override
	public Integer getId() {
		return id;
	}

	@Override
	public void setId(Integer id) {
		this.id = id;
	}

	public String getSalt() {
		return salt;
	}

	public void setSalt(String hash) {
		this.salt = hash;
	}

	public EmbeddedMutable getMutable() {
		return mutable;
	}

	public void setMutable(EmbeddedMutable mutable) {
		this.mutable = mutable;
	}
	
	@Override
    public Date getMutiertam() {
        return mutable.getMutiertam();
    }

    @Override
    public User getMutiertvon() {
        return mutable.getMutiertvon();
    }

    @Override
    public void setMutiertam(Date mutiertam) {
        mutable.setMutiertam(mutiertam);
    }

    @Override
    public void setMutiertvon(User mutiertvon) {
        mutable.setMutiertvon(mutiertvon);
    }
	
	
}

src/main/java/controller/AuswertungController.java
package controller;

import java.io.Serializable;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.faces.bean.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;

import org.primefaces.model.chart.Axis;
import org.primefaces.model.chart.AxisType;
import org.primefaces.model.chart.BarChartModel;
import org.primefaces.model.chart.ChartSeries;
import org.primefaces.model.chart.PieChartModel;

import model.Kanton;
import model.Kunde;
import service.AuswertungService;

@Named("auswertungController")
@SessionScoped
public class AuswertungController implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7601042262972196162L;

	private PieChartModel kundeProKantonPieModel;
	private BarChartModel kundeProKantonBarModel;

	@Inject
	private AuswertungService auswertungService;

	@PostConstruct
	public void createModels() {
		createPieModels();
		createBarModels();
	}

	private void createBarModels() {
		createKundeProDatumModel();
	}

	private void createPieModels() {
		createKundeProKantonModel();
	}

//	public static List<?> removeDuplicate(List<?> list) {
//		Set<?> set = listToSet(list);
//		List<?> listWithoutDuplicate = setToList(set);
//		return listWithoutDuplicate;
//	}
//
//	public static Set<?> listToSet(List<?> list) {
//		Set<Object> set = new LinkedHashSet<>();
//		set.addAll(list);
//		return set;
//	}
//
//	public static List<?> setToList(Set<?> set) {
//		List<Object> list = new ArrayList<>();
//		list.addAll(set);
//		return list;
//	}

	
	
	
	
	
	
//	public void createJasperReport() {
//		try {
//
//			ClassLoader classLoader = getClass().getClassLoader();
//			
//			System.out.println(classLoader.getResourceAsStream("reports/SampleFunctionsReport.jrxml").toString());
//			
//			classLoader.getResourceAsStream("reports/SampleFunctionsReport.jrxml");
//			
//			JasperReport jasperReport = JasperCompileManager
//					.compileReport(classLoader.getResourceAsStream("reports/SampleFunctionsReport.jrxml"));
//
//			Map<String, Object> parameters = new HashMap<String, Object>();
//			
//			JRDataSource dataSource = new JREmptyDataSource();			
//			
//			JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parameters, dataSource);
//
//			File outDir = new File("C:/Users/Egli/Desktop");
//			outDir.mkdirs();
//
//			// Export to PDF.
//			JasperExportManager.exportReportToPdfFile(jasperPrint, "C:/Users/Egli/Desktop/test.pdf");
//
//			System.out.println("Done!");
//
//		} catch (Exception e) {
//			e.printStackTrace();
//		}
//	}

	private void createKundeProDatumModel() {
		kundeProKantonBarModel = initBarModel();

		kundeProKantonBarModel.setTitle("Kunden pro Kanton");
		kundeProKantonBarModel.setLegendPosition("ne");

		Axis xAxis = kundeProKantonBarModel.getAxis(AxisType.X);
		// xAxis.setLabel("Kantone");

		Axis yAxis = kundeProKantonBarModel.getAxis(AxisType.Y);
		yAxis.setLabel("Anzahl Kunden");

		int maxKundenProKanton = 0;
		List<Kanton> kantonList = auswertungService.getKantoneFromKunden();
		for (Kanton k : kantonList) {
			List<Kunde> kundeList = auswertungService.getKundenProKanton(k);
			if (kundeList.size() > maxKundenProKanton) {
				maxKundenProKanton = kundeList.size();
			}
		}
		maxKundenProKanton += 2;
		yAxis.setMin(0);
		yAxis.setMax(maxKundenProKanton);
		yAxis.setTickInterval("1");
	}

	private BarChartModel initBarModel() {
		BarChartModel model = new BarChartModel();

		List<Kanton> kantonList = auswertungService.getKantoneFromKunden();

		System.out
				.println("AuswertungController.initBarModel() kantonListWithoutDuplicate.size(): " + kantonList.size());

		ChartSeries kantone = new ChartSeries();

		for (Kanton k : kantonList) {
			List<Kunde> kundeList = auswertungService.getKundenProKanton(k);

			kantone.setLabel(k.getText());
			kantone.set("Aufteilung Kantone", kundeList.size());

			System.out.println("AuswertungController.initBarModel() k.getText(), kundeList.size(): " + k.getText()
					+ "  " + kundeList.size());

			model.addSeries(kantone);

			kantone = new ChartSeries();
		}

		return model;
	}

	private void createKundeProKantonModel() {
		kundeProKantonPieModel = new PieChartModel();

		List<Kanton> kantonList = auswertungService.getKantoneFromKunden();

		// List<Kanton> kantonListWithoutDuplicate = (List<Kanton>)
		// removeDuplicate(kantonList);
		for (Kanton k : kantonList) {
			List<Kunde> kundeList = auswertungService.getKundenProKanton(k);

			kundeProKantonPieModel.getData().put(k.getText(), kundeList.size());

		}
		kundeProKantonPieModel.setTitle("Kunden pro Kanton");
		kundeProKantonPieModel.setLegendPosition("ne");

	}

	public PieChartModel getKundeProKantonPieModel() {
		return kundeProKantonPieModel;
	}

	public void setKundeProKantonPieModel(PieChartModel kundeProKantonModel) {
		this.kundeProKantonPieModel = kundeProKantonModel;
	}

	public BarChartModel getKundeProKantonBarModel() {
		return kundeProKantonBarModel;
	}

	public void setKundeProKantonBarModel(BarChartModel kundeProDatumModel) {
		this.kundeProKantonBarModel = kundeProDatumModel;
	}

}

src/main/webapp/pages/Auswertung.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
   "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:composite="http://java.sun.com/jsf/composite">

<h:head>
	<title>Auswertung</title>
</h:head>

<h:body>

	<p:layout fullPage="true" id="layout">
		<p:layoutUnit position="west" resizable="false" size="300">
			<ui:include src="/pages/include/menu.xhtml" />
		</p:layoutUnit>
		<p:layoutUnit position="center">

			<p:growl id="growl" autoUpdate="false" life="3000" />
			<!-- <f:metadata>
				<f:viewParam name="generateCharts" value="#{bean.foo}" />
				<f:event type="preRenderView" listener="#{bean.onload}" />
			</f:metadata> -->
			<h:form id="nameForm">
				<p:chart id="kundeProKanton" type="pie"
					model="#{auswertungController.kundeProKantonPieModel}"
					style="width:400px;height:300px" />
				<br />
				<br />
				<p:chart id="auftraegeProUser" type="bar"
					model="#{auswertungController.kundeProKantonBarModel}"
					style="height:300px" />
			</h:form>
		</p:layoutUnit>
	</p:layout>
</h:body>
</html>

src/main/webapp/pages/Benutzer.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
   "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:us="http://java.sun.com/jsf/composite/composite">

<h:head>
	<title>Benutzer</title>
</h:head>

<h:body>

	<p:layout fullPage="true" id="layout">
		<p:layoutUnit position="west" resizable="false" size="300">

			<ui:include src="/pages/include/menu.xhtml" />

		</p:layoutUnit>
		<p:layoutUnit position="center">
			<p:growl id="growl" autoUpdate="false" life="3000" />

			<h:form id="nameForm">
				<!-- <p:spacer width="100%" height="20px" /> -->

				<p:panel id="headingUser" header="Benutzer" />

				<p:dataTable id="userTable" value="#{userController.recordList}"
					var="user" widgetVar="userTable"
					filteredValue="#{userController.filteredRecordList}"
					emptyMessage="No Names found with given criteria"
					paginatorTemplate="{CurrentPageReport}  {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {Exporters}"
					paginator="true" rows="10" style="margin-bottom:20px">

					<f:facet name="{Exporters}">
						<div style="float: right; padding-top: 5px;">
							<us:exportTable id="excelExport" tableName=":nameForm:userTable"
								fileName="Benutzertabelle" type="xls"
								imageLocation="/images/excel.png" width="24" height="24" />
							<us:exportTable id="pdfExport" tableName=":nameForm:userTable"
								fileName="Benutzertabelle" type="pdf"
								imageLocation="/images/pdf.png" width="24" height="24" />

						</div>
					</f:facet>

					<p:column filterBy="#{user.id}" filterMatchMode="contains">
						<f:facet name="header">
							<h:outputText value="ID" />
						</f:facet>
						<h:outputText value="#{user.id}" />
					</p:column>


					<p:column filterBy="#{user.person.name}" filterMatchMode="contains">
						<f:facet name="header">
							<h:outputText value="Name" />
						</f:facet>
						<h:outputText value="#{user.person.name}" />
					</p:column>

					<p:column filterBy="#{user.person.vorname}"
						filterMatchMode="contains">
						<f:facet name="header">
							<h:outputText value="Vorname" />
						</f:facet>
						<h:outputText value="#{user.person.vorname}" />
					</p:column>

					<p:column>
						<h:outputText value="#{user.person.email}" />
						<f:facet name="header">
							<h:outputText value="Email" />
						</f:facet>
					</p:column>

					<p:column id="commandButtons" exportable="false"
						style="width:150px; text-align:center;">
						<p:commandButton id="buttonEdit" icon="ui-icon-pencil"
							oncomplete="PF('editDialog').show();" update=":editDialogForm"
							actionListener="#{userController.setSelectedRecord(user)}">
						</p:commandButton>
						<p:commandButton id="buttonRemove" icon="ui-icon-trash"
							update=":ccRemove:removeDialogForm"
							oncomplete="PF('removeDialog').show();"
							actionListener="#{userController.setSelectedRecord(user)}">
						</p:commandButton>
					</p:column>
				</p:dataTable>



				<p:spacer width="100%" height="20px" />
				<div style="float: right;">
					<p:commandButton value="Neuer Benutzer"
						actionListener="#{userController.create()}"
						oncomplete="PF('editDialog').show();" update=":editDialogForm" />

				</div>


				<p:blockUI widgetVar="blockForm" block="nameForm">
					<!-- trigger="submit" -->
					<h:outputText value="Laden" />

				</p:blockUI>
			</h:form>

			<p:dialog appendTo="@(body)" id="editDialog"
				header="#{empty userController.selectedRecord ? 'selectedRecord is null' : 'selectedRecord is not null'}"
				widgetVar="editDialog" modal="true">
				<h:form id="editDialogForm">
					<f:metadata>
						<f:event type="preRenderView"
							listener="#{userReflection.setExcludetFields('passwordHashed', 'salt', 'serialVersionUID', 'id')}" />
					</f:metadata>
					<p:panel id="dialogPanel">
						<p:panelGrid>


							<!-- <h:panelGrid columns="2"> -->

							<ui:repeat var="field" value="#{userReflection.fields}">
								<p:row>
									<p:column>
										<p:outputLabel value="#{field.getName()}" />
									</p:column>
									<p:column>
										<p:inputText required="true"
											rendered="#{field.getGenericType().toString() eq 'class java.lang.String'}"
											value="#{userController.selectedRecord[field.getName()]}">
										</p:inputText>
										<p:selectOneMenu converter="#{personConverter}"
											rendered="#{field.getGenericType().toString() eq 'class model.Person'}"
											value="#{userController.selectedRecord[field.getName()]}">
											<f:selectItem itemLabel="Person wählen" itemValue="#{null}"
												itemDisabled="#{true}" />
											<f:selectItems value="#{personController.recordList}" var="r"
												itemLabel="#{r.fullName}" itemValue="#{r}" />
											<p:ajax update="editDialogForm:submitEdit" />
										</p:selectOneMenu>
										<p:calendar
											value="#{userController.selectedRecord[field.getName()]}"
											rendered="#{field.getGenericType().toString() eq 'class java.util.Date' and field.getName() eq 'mutiertam'}"
											mode="inline" />
									</p:column>
								</p:row>
							</ui:repeat>
							<p:row>
								<p:column colspan="2" style="text-align: center;">
									<p:commandButton id="submitEdit" icon="ui-icon-disk"
										validateClient="true" value="speichern"
										actionListener="#{userController.saveUser()}"
										oncomplete="PF('editDialog').hide(); PF('userTable').filter()"
										update="@form :growl" />
								</p:column>
							</p:row>
							<!-- </h:panelGrid> -->
						</p:panelGrid>
					</p:panel>
				</h:form>
			</p:dialog>


			<!-- 
			<us:editDialog id="editDialogComposite" namedController="#{userController}" entityName="user"
				tableName="userTable" />

 -->
			<us:removeDialog id="ccRemove" namedController="#{userController}"
				tableName="userTable" />

			<!-- 

			</c:if>
			<c:if test="#{not helloUser.loginCorrect}">
				<h:form>
					<p:remoteCommand name="onload"
						action="#{helloUser.unauthorizedUser('Kunden')}" autoRun="true" />
				</h:form>
			</c:if>
 -->
		</p:layoutUnit>
	</p:layout>
</h:body>
</html>

src/main/webapp/pages/Kantone.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
   "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
	xmlns:p="http://primefaces.org/ui">

<h:head>
	<title>Kantone</title>
</h:head>

<h:body>

	<p:layout fullPage="true" id="layout">
		<p:layoutUnit position="west" resizable="false" size="300">
		
		
			<ui:include src="/pages/include/menu.xhtml" />
			
			
		</p:layoutUnit>
		<p:layoutUnit position="center">
			<!-- 
			<c:if test="#{helloUser.loginCorrect}">
			
-->
			<p:growl id="growl" autoUpdate="false" life="3000" />

			<h:form id="nameForm">
				<!-- <p:spacer width="100%" height="20px" /> -->

				<p:panel id="headingKantone" header="Kantone" />

				<p:dataTable id="kantoneTable" value="#{kantonController.recordList}"
					var="kanton" widgetVar="kantoneTable"
					filteredValue="#{kantonController.filteredRecordList}"
					emptyMessage="No Names found with given criteria">

					<p:column headerText="ID" filterBy="#{kanton.id}"
						filterMatchMode="contains">
						<h:outputText value="#{kanton.id}" />
					</p:column>

					<p:column headerText="Kanton"
						filterBy="#{kanton.kurzbezeichnung}"
						filterMatchMode="contains">
						<f:facet name="filter">
							<p:selectOneMenu onchange="PF('kantoneTable').filter()">
								<f:selectItem itemLabel="Select One" itemValue="#{null}"
									noSelectionOption="true" />
								<f:selectItems value="#{kantonController.recordList}" />
							</p:selectOneMenu>
						</f:facet>
						<h:outputText value="#{kanton.kurzbezeichnung}" />
					</p:column>

					<p:column headerText="Text" filterBy="#{kanton.text}"
						filterMatchMode="contains" footerText="contains">
						<h:outputText value="#{kanton.text}" />
					</p:column>
					
					<p:column id="commandButtons" exportable="false"
						style="width:150px; text-align:center;">
						<p:commandButton id="buttonEdit" icon="ui-icon-pencil"
							update=":editDialogForm" oncomplete="PF('editDialog').show();"
							actionListener="#{kantonController.setSelectedRecord(kanton)}">
						</p:commandButton>
						<p:commandButton id="buttonRemove" icon="ui-icon-trash"
							update=":growl :nameForm" oncomplete="PF('kantoneTable').filter()">
							<f:setPropertyActionListener value="#{kanton}"
								target="#{kantonController.selectedRecord}" />
							<f:actionListener binding="#{kantonController.removeKanton()}" />

						</p:commandButton>
					</p:column>
				</p:dataTable>

				<p:spacer width="100%" height="20px" />
				<div style="float: right;">
					<p:commandButton value="Neuer Kanton" update=":editDialogForm"
						actionListener="#{kantonController.create()}"
						oncomplete="PF('editDialog').show();" />

				</div>


				<p:blockUI widgetVar="blockForm" block="nameForm">
					<!-- trigger="submit" -->
					<h:outputText value="Laden" />

				</p:blockUI>
			</h:form>

			<p:dialog appendTo="@(body)" id="editDialog"
				header="#{empty kantonController.selectedRecord ? 'selectedRecord is null' : 'selectedRecord is not null'}"
				widgetVar="editDialog" modal="true">
				<h:form id="editDialogForm">
					<h:panelGrid columns="3">

						<p:panel id="dialogPanel">
							<h:panelGrid columns="2">

								<p:outputLabel  value="Kurzbezeichnung" />
								<p:inputText  required="true"
									value="#{kantonController.selectedRecord.kurzbezeichnung}">
								</p:inputText>

								<p:outputLabel for="textEdit" value="Text" />
								<p:inputText id="textEdit" required="true"
									value="#{kantonController.selectedRecord.text}">
								</p:inputText>
								

								<p:spacer width="100%" height="10px" />


								<p:commandButton id="submitEdit" icon="ui-icon-disk"
									validateClient="true" value="speichern"
									actionListener="#{kantonController.saveKanton()}"
									oncomplete="if (args &amp;&amp; !args.validationFailed) { PF('editDialog').hide(); PF('kantoneTable').filter()}"
									update="@form :growl" />

							</h:panelGrid>
						</p:panel>
					</h:panelGrid>
				</h:form>
			</p:dialog>
			<!-- 

			</c:if>
			<c:if test="#{not helloUser.loginCorrect}">
				<h:form>
					<p:remoteCommand name="onload"
						action="#{helloUser.unauthorizedUser('Kunden')}" autoRun="true" />
				</h:form>
			</c:if>
 -->
		</p:layoutUnit>
	</p:layout>
</h:body>
</html>

src/main/webapp/pages/Kunden.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
   "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:us="http://java.sun.com/jsf/composite/composite">

<h:head>
	<title>Kunden</title>
</h:head>

<h:body>

	<p:layout fullPage="true" id="layout">
		<p:layoutUnit position="west" resizable="false" size="300">
			<ui:include src="/pages/include/menu.xhtml" />
		</p:layoutUnit>
		<p:layoutUnit position="center">
			<!-- 
			<c:if test="#{helloUser.loginCorrect}">
			
-->
			<p:growl id="growl" autoUpdate="false" life="3000" />

			<h:form id="nameForm">
				<!-- <p:spacer width="100%" height="20px" /> -->

				<p:panel id="headingKunden" header="Kunden" />

				<p:dataTable id="kundenTable" value="#{kundeController.recordList}"
					var="kunde" widgetVar="kundenTable"
					filteredValue="#{kundeController.filteredRecordList}"
					emptyMessage="No Names found with given criteria">

					<p:column headerText="ID" filterBy="#{kunde.id}"
						filterMatchMode="contains">
						<h:outputText value="#{kunde.id}" />
					</p:column>

					<p:column headerText="Kanton"
						filterBy="#{kunde.kanton}"
						filterMatchMode="contains">
						<f:facet name="filter">
							<p:selectOneMenu onchange="PF('kundenTable').filter()">
								<f:selectItem itemLabel="Select One" itemValue="#{null}"
									noSelectionOption="true" />
								<f:selectItems value="#{kantonController.recordList}" var="r"
									itemLabel="#{r.kurzbezeichnung}" />
							</p:selectOneMenu>
						</f:facet>
						<h:outputText value="#{kunde.kanton.kurzbezeichnung}" />
					</p:column>

					<p:column headerText="Name" filterBy="#{kunde.person.name}"
						filterMatchMode="contains" footerText="contains">
						<h:outputText value="#{kunde.person.name}" />
					</p:column>

					<p:column headerText="Vorname" filterBy="#{kunde.person.vorname}"
						filterMatchMode="contains" footerText="contains">
						<h:outputText value="#{kunde.person.vorname}" />
					</p:column>

					<p:column headerText="E-Mail" footerText="email">
						<h:outputText value="#{kunde.person.email}" />
					</p:column>

					<p:column id="commandButtons"
						style="width:150px; text-align:center;">
						<p:commandButton id="buttonEdit" icon="ui-icon-pencil"
							update="editDialogComposite:editDialogForm" oncomplete="PF('editDialog').show();"
							actionListener="#{kundeController.setSelectedRecord(kunde)}">
						</p:commandButton>
						<p:commandButton id="buttonRemove" icon="ui-icon-trash"
							update=":growl :nameForm" oncomplete="PF('kundenTable').filter()">
							<f:setPropertyActionListener value="#{kunde}"
								target="#{kundeController.selectedRecord}" />
							<f:actionListener binding="#{kundeController.removeKunde()}" />

						</p:commandButton>
					</p:column>
				</p:dataTable>

				<p:spacer width="100%" height="20px" />
				<div style="float: right;">
					<p:commandButton value="Neuer Kunde" update="editDialogComposite:editDialogForm"
						actionListener="#{kundeController.create()}"
						oncomplete="PF('editDialog').show();" />

				</div>


				<p:blockUI widgetVar="blockForm" block="nameForm">
					<!-- trigger="submit" -->
					<h:outputText value="Laden" />

				</p:blockUI>
			</h:form>

			<us:editDialog id="editDialogComposite" namedController="#{kundeController}" entityName="kunden"
				tableName="kundenTable" />


			<us:removeDialog id="ccRemove" namedController="#{userController}"
				tableName="userTable" />

			<!-- 

			</c:if>
			<c:if test="#{not helloUser.loginCorrect}">
				<h:form>
					<p:remoteCommand name="onload"
						action="#{helloUser.unauthorizedUser('Kunden')}" autoRun="true" />
				</h:form>
			</c:if>
 -->
		</p:layoutUnit>
	</p:layout>
</h:body>
</html>